[package]
name = "esprit-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version = "0.24.5", optional = true }

[[bin]]
name = "makefont"
required-features = ["image"]
